//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DVD
    {
        public int DvdId { get; set; }
        public string DvdTitle { get; set; }
        public string DvdSummary { get; set; }
        public string DvdRating { get; set; }
    }
}
