//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int memberId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> Phonenumber { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    }
}
